import React from 'react';


// Imports the Amplify library from 'aws-amplify' package. This is used to configure your app to interact with AWS services.
import {Amplify} from 'aws-amplify';

// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
import { Authenticator, withAuthenticator } from '@aws-amplify/ui-react';

// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from './aws-exports';

// Imports the Quiz component from Quiz.js for use in this file.

import ModernBlogGenerator from './ModernBlogGenerator';

// Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.
Amplify.configure(awsExports);

function App() {
  return (
    <div className="App">
      <Authenticator>
        {({ signOut }) => (
          <main>
            {/* Modern Navigation Bar */}
            <nav style={{
              width: '100%',
              background: '#23272f',
              color: '#fff',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '0.5rem 1.5rem',
              boxShadow: '0 2px 10px 0 rgba(32,38,58,0.07)',
              position: 'fixed',
              top: 0,
              left: 0,
              zIndex: 1000,
              minHeight: 48,
              borderRadius: '0 0 12px 12px',
              borderBottom: '1.5px solid #26304a',
            }}>
              <span style={{ fontSize: '1.25rem', fontWeight: 700, letterSpacing: '0.03em', color: '#3a86ff', paddingLeft: 4 }}>Blog Generator</span>
              <button
                onClick={signOut}
                style={{
                  background: 'linear-gradient(90deg,#3a86ff 60%,#2d8fa7 100%)',
                  color: '#fff',
                  border: 'none',
                  borderRadius: '0.4rem',
                  padding: '0.4rem 1.1rem',
                  fontSize: '0.98rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                  boxShadow: '0 1.5px 6px 0 rgba(32,38,58,0.10)',
                  transition: 'background 0.2s, color 0.2s',
                  outline: 'none',
                }}
              >
                Sign Out
              </button>
            </nav>
            {/* Main Content */}
            <div style={{ marginTop: 90 }}>
              <ModernBlogGenerator />
            </div>
          </main>
        )}
      </Authenticator>
    </div>
  );
}

export default withAuthenticator(App);