// ModernBlogGenerator styles as a JS object
const styles = {
  container: {
    background: '#fff',
    padding: '3.5rem 3rem',
    borderRadius: '1.5rem',
    boxShadow: '0 8px 32px 0 rgba(35, 41, 70, 0.08)',
    maxWidth: 950,
    width: '100%',
    textAlign: 'center',
    margin: '2.5rem auto',
    animation: 'fadeIn 1.2s cubic-bezier(.39,.575,.56,1) both',
  },
  heading: {
    color: '#3a86ff',
    marginBottom: '1.5rem',
    fontSize: '2rem',
  },
  subheading: {
    color: '#555',
    marginBottom: '2rem',
    fontSize: '1.1rem',
  },
  inputRow: {
    marginBottom: '1.5rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '0.5rem',
  },
  input: {
    maxWidth: 400,
    width: '90%',
    padding: '0.7rem',
    borderRadius: '0.5rem',
    border: '1px solid #bdbdbd',
    fontSize: '1rem',
    marginBottom: '1.2rem',
    outline: 'none',
    transition: 'border 0.3s',
  },
  button: {
    background: '#2a7be4',
    color: '#fff',
    border: 'none',
    padding: '0.8rem 2rem',
    borderRadius: '0.5rem',
    fontSize: '1rem',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 4px 14px 0 rgba(32,38,58,0.07)',
    marginBottom: '1.5rem',
    transition: 'background 0.3s, transform 0.2s, color 0.2s',
  },
  loader: {
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #3a86ff',
    borderRadius: '50%',
    width: 32,
    height: 32,
    animation: 'spin 1s linear infinite',
    margin: '1rem auto',
  },
  output: {
    background: '#f7f9fc',
    borderRadius: '0.75rem',
    padding: '1.5rem 2rem',
    minHeight: 120,
    boxShadow: '0 2px 16px 0 rgba(32, 38, 58, 0.06)',
    color: '#222b45',
    fontSize: '1.13rem',
    textAlign: 'left',
    marginTop: '1.2rem',
    whiteSpace: 'pre-line',
    width: '100%',
    maxWidth: 640,
    marginLeft: 'auto',
    marginRight: 'auto',
    lineHeight: 1.7,
  },
  pastBlogsHeading: {
    marginTop: '2.5rem',
    color: '#2d8fa7',
  },
  pastBlogsOutput: {
    minHeight: 60,
    background: '#f8f9fd',
  },
  blogLink: {
    display: 'inline-block',
    margin: '0 0.7rem 1rem 0',
    fontWeight: 700,
    color: '#2d8fa7',
    textDecoration: 'underline',
    fontSize: '1.1rem',
    cursor: 'pointer',
  },
  error: {
    color: 'red',
    marginBottom: '1rem',
  },
  footer: {
    marginTop: '2rem',
    color: '#7d8597',
    fontSize: '0.97rem',
    letterSpacing: '0.02em',
  },
};

export default styles;
